In [1]:
from db import db_connect

con = db_connect()

q = """
    DELETE FROM User 
    WHERE user_id = "2c27c4b819feb4637f70cf6bdfb450d7b0832973cd13cdaac3ccd7de8d61c45a";
"""

con.execute(q)
con.commit()  # 변경사항을 저장합니다.
con.close()   # 연결을 닫습니다.

In [1]:
from db import db_connect

con = db_connect()
q = '''
CREATE TABLE IF NOT EXISTS friend (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id1 TEXT NOT NULL,
    user_id2 TEXT NOT NULL,
    mutality BOOLEAN NOT NULL DEFAULT 0,
    UNIQUE(user_id1, user_id2)
)
'''

con.execute(q)
con.commit()  # 변경사항을 저장합니다.
con.close()   # 연결을 닫습니다.

In [4]:
from db import db_connect

con = db_connect()
q = '''
DROP TABLE IF EXISTS friend
'''

con.execute(q)
con.commit()  # 변경사항을 저장합니다.
con.close()   # 연결을 닫습니다.

In [6]:
from db import db_connect
import sqlite3


def get_table_info():
    con = db_connect()
    cursor = con.cursor()

    # 테이블 정보 조회
    cursor.execute("PRAGMA table_info(LectureTable)")
    columns = cursor.fetchall()

    print("User 테이블 구조:")
    for col in columns:
        print(f"컬럼명: {col[1]}, 데이터 타입: {col[2]}")

    con.close()
    print(type(columns))
    return columns

In [3]:
from db import db_connect

con = db_connect()

q = """
    DELETE FROM friend 
    WHERE user_id2 = "2c27c4b819feb4637f70cf6bdfb450d7b0832973cd13cdaac3ccd7de8d61c45a";
"""

q = """
    INSERT INTO friend (user_id1, user_id2, mutality)
    VALUES ("d9a03f5edb98b56cdc99dd95c63a90d648b555ade6354a8aa9396d20918e6bfd", "2c27c4b819feb4637f70cf6bdfb450d7b0832973cd13cdaac3ccd7de8d61c45a", 0);
"""

con.execute(q)
con.commit()  # 변경사항을 저장합니다.
con.close()   # 연결을 닫습니다.

In [2]:

con = db_connect()

q = """
INSERT INTO User (
    user_id,
    hakBun,
    isForeign,
    bunBan,
    userYear,
    userMajor,
    isMultipleMajor,
    whatMultipleMajor,
    userName,
    majorGPA,
    totalGPA
) VALUES (
    "2c27c4b819feb4637f70cf6bdfb450d7b0832973cd13cdaac3ccd7de8d61c45a",
    2021204066,
    0,
    'c8',
    4,
    '정보융합학부',
    0,
    '',
    '손원택',
    4.0,
    4.0
)
"""
con.execute(q)
con.commit()  # 변경사항을 저장합니다.
con.close()   # 연결을 닫습니다.

In [3]:

con = db_connect()

q = """
INSERT INTO User (
    hakBun,
    isForeign,
    bunBan,
    userYear,
    userMajor,
    isMultipleMajor,
    whatMultipleMajor,
    userName,
    majorGPA,
    totalGPA, user_id)
SELECT     hakBun,
    isForeign,
    bunBan,
    userYear,
    userMajor,
    isMultipleMajor,
    whatMultipleMajor,
    userName,
    majorGPA,
    totalGPA,  '104216379361715837223' as user_id
FROM User
WHERE user_id = '103959235418219219272';
"""
con.execute(q)
con.commit()  # 변경사항을 저장합니다.
con.close()   # 연결을 닫습니다.

In [5]:
import sqlite3

DATABASE = './kwu-lecture-database-v8.db'


def db_connect():
    conn = sqlite3.connect(DATABASE)
    conn.row_factory = sqlite3.Row
    return conn


def get_lecture_table_schema():
    conn = db_connect()
    cursor = conn.cursor()

    # LectureTable의 스키마 정보를 가져오는 쿼리
    cursor.execute("PRAGMA table_info(LectureTable)")

    # 결과 출력
    print("LectureTable 스키마:")
    print("--------------------")
    for column in cursor.fetchall():
        print(f"칼럼명: {column['name']}, 데이터 타입: {column['type']}")

    conn.close()


if __name__ == "__main__":
    get_lecture_table_schema()

LectureTable 스키마:
--------------------
칼럼명: lecNumber, 데이터 타입: INTEGER
칼럼명: year, 데이터 타입: INTEGER
칼럼명: semester, 데이터 타입: TEXT
칼럼명: lecUrl, 데이터 타입: TEXT
칼럼명: lecClassification, 데이터 타입: TEXT
칼럼명: lecClassName, 데이터 타입: TEXT
칼럼명: lecSubName, 데이터 타입: TEXT
칼럼명: lecProfessor, 데이터 타입: TEXT
칼럼명: lecStars, 데이터 타입: FLOAT
칼럼명: lecAssignment, 데이터 타입: FLOAT
칼럼명: lecTeamplay, 데이터 타입: FLOAT
칼럼명: lecGrade, 데이터 타입: FLOAT
칼럼명: lecSummaryReview, 데이터 타입: TEXT
칼럼명: lecAttend, 데이터 타입: TEXT
칼럼명: lecTestNum, 데이터 타입: TEXT
칼럼명: lecLastYear1PeopleNum, 데이터 타입: INTEGER
칼럼명: lecLastYear2PeopleNum, 데이터 타입: INTEGER
칼럼명: lecLastYear3PeopleNum, 데이터 타입: INTEGER
칼럼명: lecIsPNP, 데이터 타입: BOOLEAN
칼럼명: lecIsEngeneering, 데이터 타입: BOOLEAN
칼럼명: lecRequirementClass, 데이터 타입: TEXT
칼럼명: lecForeignLanguageRatio, 데이터 타입: TEXT
칼럼명: lecException, 데이터 타입: TEXT
칼럼명: lecTakeOnly1Year, 데이터 타입: INTEGER
칼럼명: lecTakeOnly2Year, 데이터 타입: INTEGER
칼럼명: lecTakeOnly3Year, 데이터 타입: INTEGER
칼럼명: lecTakeOnly4Year, 데이터 타입: INTEGER
칼럼명: lecTakeOnly5Year, 데이터 타입: INTEGER
칼럼명: lecCredit, 데이터 타입: INTEGER
칼럼명: lecWeekHours, 데이터 타입: INTEGER
칼럼명: lecForeignPeopleCanTake, 데이터 타입: BOOLEAN
칼럼명: lecCanTakeMultipleMajor, 데이터 타입: BOOLEAN
칼럼명: lecTakeOnlyAthletics, 데이터 타입: BOOLEAN
칼럼명: lecTakeOnlyChambit, 데이터 타입: BOOLEAN
칼럼명: lecLinkedMajorDifficulty, 데이터 타입: TEXT
칼럼명: lecMoreInfo, 데이터 타입: TEXT
칼럼명: lecCanTakeBunban, 데이터 타입: TEXT
칼럼명: lecMajorRecogBunban, 데이터 타입: TEXT
칼럼명: lecTime, 데이터 타입: TEXT
칼럼명: lecEvaluateRatio, 데이터 타입: TEXT
칼럼명: lecOverview, 데이터 타입: TEXT
칼럼명: lecIsEng, 데이터 타입: BOOLEAN
칼럼명: lecIsCn, 데이터 타입: BOOLEAN
칼럼명: lecIsJp, 데이터 타입: BOOLEAN
칼럼명: lecIsTBL, 데이터 타입: BOOLEAN
칼럼명: lecIsPBL, 데이터 타입: BOOLEAN
칼럼명: lecIsSeminar, 데이터 타입: BOOLEAN
칼럼명: lecIsSmall, 데이터 타입: BOOLEAN
칼럼명: lecIsConvergence, 데이터 타입: BOOLEAN
칼럼명: lecIsTeamTeach, 데이터 타입: BOOLEAN
칼럼명: lecIsWorkStudyCombine, 데이터 타입: BOOLEAN
칼럼명: lecIseLearning, 데이터 타입: BOOLEAN
칼럼명: lecIsExperimentDesign, 데이터 타입: BOOLEAN
칼럼명: lecIsFocus, 데이터 타입: BOOLEAN
칼럼명: lecIsDistance100, 데이터 타입: BOOLEAN
칼럼명: lecIsDistance50, 데이터 타입: BOOLEAN
칼럼명: lecIsFace, 데이터 타입: BOOLEAN
칼럼명: lecIsOnline, 데이터 타입: BOOLEAN
칼럼명: lecIsRecorded, 데이터 타입: BOOLEAN
칼럼명: lecIsDoExperiment, 데이터 타입: BOOLEAN
칼럼명: lecIsDiscussion, 데이터 타입: BOOLEAN
칼럼명: lecIsArt, 데이터 타입: BOOLEAN
칼럼명: lecClassRoom, 데이터 타입: TEXT