### 2차 전처리
* 1. 중복값처리 ex. 매치업 (교양파일과 전공파일에 모두 존재)

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\user\Desktop\df_result.csv", encoding="cp949")

In [2]:
df

,Unnamed: 0,학정번호,과목명,분반,학년,연계,이수,학점,시수,담당교수,"강의시간 (요일,교시)",강의유형,외국인재학생,국내재학생,선수과목
0,0,0000-1-8128-01,광운인되기,외국인학생 수강불가,NaN,Null,교필,1,1,김정권,Null,"원격수업100,융합강의 1학기 또는 2학기 이수",NaN,NaN,NaN
1,1,0000-1-8128-02,광운인되기,외국인만 수강가능,NaN,Null,교선,1,1,한재현,금2,외국인전용,NaN,NaN,NaN
2,2,7000-1-3362-01,대학영어,"전자정보 공과대학 공통(E1~E8,J1~J4, T1~T2)",NaN,Null,교필,3,3,고현아,"월1,수2",Null,NaN,NaN,NaN
3,3,7000-1-3362-02,대학영어,"전자정보 공과대학 공통(E1~E8,J1~J4, T1~T2)",NaN,Null,교필,3,3,신동선,"월2,수1",Null,NaN,NaN,NaN
4,4,7000-1-3362-03,대학영어,"전자정보 공과대학 공통(E1~E8,J1~J4, T1~T2)",NaN,Null,교필,3,3,조성은,"월3,수4",Null,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1643,1643,0000-2-5062-06,KW-VIP 2024-1(친환경 플라즈마 의과학 시스템 개발),Null,NaN,Null,일선,2,2,최은하,Null,Null,NaN,NaN,NaN
1644,1644,0000-2-5062-07,KW-VIP 2024-1(전기화학 센서 및 에너지 시스템),Null,NaN,Null,일선,2,2,김양래,Null,Null,NaN,NaN,NaN
1645,1645,0000-2-5062-08,KW-VIP 2024-1(구리 촉매 시스템을 사용한 유기 반응 개발),Null,NaN,Null,일선,2,2,이윤미,Null,Null,NaN,NaN,NaN
1646,1646,0000-2-5062-09,KW-VIP 2024-1(전문 헬스케어 인재 육성 프로그램),Null,NaN,Null,일선,2,2,박석,Null,Null,NaN,NaN,NaN
1647,1647,0000-2-5062-10,KW-VIP 2024-1(미래 모빌리티 사용자 경험 연구),Null,NaN,Null,일선,2,2,황동욱,Null,Null,NaN,NaN,NaN

In [20]:
column_name = '학정번호'
duplicate_values = df[column_name][df[column_name].duplicated(keep=False)]

duplicate_counts = duplicate_values.value_counts()

print("중복된 수치값과 그 개수:")
print(duplicate_counts)

중복된 수치값과 그 개수:
학정번호
0000-1-4628-04    3
0000-1-8128-01    2
0000-1-4625-19    2
0000-1-4625-20    2
0000-1-4625-21    2
0000-1-4625-22    2
0000-1-4625-23    2
0000-1-4625-24    2
0000-1-4625-25    2
0000-1-4625-26    2
0000-1-4626-01    2
0000-1-4626-02    2
0000-1-4628-01    2
0000-1-4628-02    2
0000-1-4628-03    2
0000-1-4628-05    2
0000-2-4969-12    2
0000-1-4628-06    2
0000-1-0109-01    2
0000-1-0109-02    2
0000-2-4969-01    2
0000-2-4969-02    2
0000-2-4969-03    2
0000-2-4969-04    2
0000-2-4969-05    2
0000-2-4969-06    2
0000-2-4969-07    2
0000-2-4969-08    2
0000-2-4969-09    2
0000-2-4969-10    2
0000-1-4625-18    2
0000-1-4625-17    2
0000-1-4625-16    2
0000-1-4625-15    2
0000-2-9251-02    2
0000-3-5765-01    2
0000-1-5660-02    2
0000-1-2959-03    2
0000-1-5901-01    2
0000-1-5901-02    2
0000-1-3363-02    2
0000-2-8834-03    2
0000-3-9448-01    2
0000-1-3593-15    2
0000-1-2950-10    2
0000-1-4837-02    2
0000-3-3200-03    2
0000-1-4625-01    2
0000-1-4625-02    2
0000-1-4625-03    2
0000-1-4625-04    2
0000-1-4625-05    2
0000-1-4625-06    2
0000-1-4625-07    2
0000-1-4625-08    2
0000-1-4625-09    2
0000-1-4625-10    2
0000-1-4625-11    2
0000-1-4625-12    2
0000-1-4625-13    2
0000-1-4625-14    2
0000-2-4969-11    2
0000-2-4969-13    2
0000-2-5714-01    2
5080-2-4964-01    2
0000-1-5220-02    2
0000-1-3415-01    2
0000-1-3415-02    2
0000-1-3415-03    2
0000-1-3415-04    2
0000-1-3415-05    2
0000-1-7466-01    2
0000-1-7466-02    2
0000-1-7466-03    2
0000-1-1223-01    2
0000-1-1223-02    2
0000-1-6527-01    2
0000-1-6527-02    2
6050-2-4903-01    2
0000-2-4969-14    2
5080-2-4965-01    2
I020-2-4888-01    2
7000-1-4651-01    2
7000-3-7905-01    2
7000-4-8478-01    2
I000-1-4651-01    2
I000-3-7905-01    2
1000-1-4651-01    2
1000-2-8584-01    2
1000-3-3270-01    2
1000-3-7905-01    2
1000-3-8831-01    2
5080-4-7882-01    2
0000-1-5220-01    2
0000-1-9753-08    2
0000-1-9753-07    2
0000-1-9753-06    2
0000-2-4969-15    2
0000-2-7724-01    2
0000-3-0819-01    2
0000-3-0819-02    2
0000-3-0819-03    2
0000-3-0819-04    2
0000-3-1942-01    2
0000-3-1942-02    2
0000-3-8120-01    2
0000-1-3414-01    2
0000-1-3414-02    2
0000-1-3414-03    2
0000-1-3414-04    2
0000-1-3414-05    2
0000-1-3414-06    2
0000-1-3414-07    2
0000-1-3414-08    2
0000-1-3414-09    2
0000-1-3414-10    2
0000-1-3414-11    2
0000-1-3414-12    2
0000-1-3414-13    2
0000-1-9753-01    2
0000-1-9753-02    2
0000-1-9753-03    2
0000-1-9753-04    2
0000-1-9753-05    2
0000-2-5714-02    2
0000-1-4101-03    2
0000-1-8128-02    2
I000-1-3095-14    2
I000-1-3095-01    2
I000-1-3095-02    2
I000-1-3095-03    2
I000-1-3095-04    2
I000-1-3095-05    2
I000-1-3095-06    2
I000-1-3095-07    2
I000-1-3095-08    2
I000-1-3095-09    2
I000-1-3095-10    2
I000-1-3095-11    2
I000-1-3095-12    2
I000-1-3095-13    2
1000-1-3095-01    2
5000-1-3095-02    2
1000-1-3095-02    2
1000-1-3095-03    2
1000-1-3095-04    2
1000-1-3095-05    2
1000-1-3095-06    2
3000-1-3095-01    2
3000-1-3095-02    2
3000-1-3095-03    2
3000-1-3095-04    2
3000-1-3095-05    2
3000-1-3095-06    2
3000-1-3095-07    2
3000-1-3095-08    2
0000-1-3362-01    2
F000-1-3362-07    2
F000-1-3362-06    2
F000-1-3362-05    2
7000-1-3362-01    2
7000-1-3362-02    2
7000-1-3362-03    2
7000-1-3362-04    2
7000-1-3362-05    2
7000-1-3362-06    2
7000-1-3362-07    2
7000-1-3362-08    2
7000-1-3362-09    2
7000-1-3362-10    2
7000-1-3362-11    2
7000-1-3362-12    2
7000-1-3362-13    2
7000-1-3362-14    2
7000-1-3362-15    2
7000-1-3362-16    2
7000-1-3362-17    2
6000-1-3362-01    2
6000-1-3362-02    2
6000-1-3362-03    2
6000-1-3362-04    2
6000-1-3362-05    2
6000-1-3362-06    2
F000-1-3362-01    2
F000-1-3362-02    2
F000-1-3362-03    2
F000-1-3362-04    2
5000-1-3095-01    2
5000-1-3095-03    2
0000-2-3679-01    2
3000-1-4432-05    2
1000-1-4432-02    2
1000-1-4432-03    2
1000-1-4432-04    2
1000-1-4432-05    2
6000-1-4432-01    2
6000-1-4432-02    2
6000-1-4432-03    2
6000-1-4432-04    2
6000-1-4432-05    2
3000-1-4432-01    2
3000-1-4432-02    2
3000-1-4432-03    2
3000-1-4432-04    2
3000-1-4432-06    2
5000-1-3095-04    2
3000-1-4432-07    2
F000-1-4432-01    2
F000-1-4432-02    2
F000-1-4432-03    2
F000-1-4432-04    2
F000-1-4432-05    2
5000-1-4432-01    2
5000-1-4432-02    2
5000-1-4432-03    2
5000-1-4432-04    2
5000-1-4432-05    2
0000-1-4929-01    2
0000-1-3403-01    2
1000-1-4432-01    2
I040-1-8610-03    2
I040-1-8610-02    2
I040-1-8610-01    2
5000-1-3095-05    2
5000-1-3095-06    2
5000-1-3095-07    2
7060-1-0019-01    2
7060-1-0019-02    2
7060-1-0019-03    2
7060-1-0019-04    2
7070-1-0019-01    2
7070-1-0019-02    2
7420-1-0019-01    2
7420-1-0019-02    2
7320-1-0019-01    2
7320-1-0019-02    2
7340-1-0019-01    2
7340-1-0019-02    2
7460-1-0019-01    2
7460-1-0019-02    2
I020-1-0019-01    2
I020-1-0019-02    2
I020-1-0019-03    2
I030-1-0019-01    2
I030-1-0019-02    2
I030-1-0019-03    2
I050-1-0019-01    2
I050-1-0019-02    2
I050-1-0019-03    2
I050-1-0019-04    2
5100-2-8081-01    2
Name: count, dtype: int64